# -*- coding: utf-8 -*-
"""RespostaEstadoNulo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pINOeAUOnD7aor8chu0MktffwGLmKLgY

Resposta ao estado nulo
"""

import sympy as sp

# Definindo t como símbolo
t, tau = sp.symbols('t tau')

# Definindo as funções h(tau) e x(tau)
h_tau = 3*sp.exp(-6*tau) + sp.exp(-tau)
x_tau = sp.exp(tau)

# Definindo a convolução y(t)
convolution = sp.integrate(x_tau * h_tau.subs(tau, t - tau), (tau, 0, t))

# Exibindo a equação y(t)
print("y(t) = ", convolution.simplify())

# Avaliando y(t) para t = 1
t_value = 1
y_value = convolution.subs(t, t_value)
print(f"y({t_value}) =", y_value.evalf())