# -*- coding: utf-8 -*-
"""calcula_InversaLaplace.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BUP_6AUnajXxemMe1SzA89gU86jaaOeg
"""

# Importando o modulo SymPy que faz trata de Cálculo Avançado
import sympy

# Definir o simbolo das funções no domínio 's'
s, t = sympy.symbols('s, t')
#t = sympy.symbols('t')


# Definir a função interna SymPy que calcula da Transformada Inversa de Laplace
def Inversa(F):
    return sympy.inverse_laplace_transform(F, s, t, noconds=True)

# Especificando da função no domínio 's' a ser calculada
F = 1/(s**2-2*s-3)

# Decompõe a função F, especificada anteriormente, em fracoes parciais
fracoes_parciais = F.apart(s)

# Cálculo da TIL da função decomposta em frações parciais
Inversa(fracoes_parciais)





