# -*- coding: utf-8 -*-
"""Resposta em Frequencia_BODE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lKKe-Xus7GU16pVdV5jGpPkbgz3bTG5J
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

# Trazer o módulo SymPy
import sympy
from sympy import *
from sympy.physics.control.lti import TransferFunction
from sympy.physics.control.control_plots import bode_plot # Plotar o diagrama de Bode
s = symbols('s')
c, C = symbols('c C', cls = Function)

# Print mais bonito no SymPy
init_printing(use_unicode=True)

# Condicoes Iniciais - NULAS
y0 = 0
dy_0 = 0

# Defina aqui a equação diferencial no domínio 's'
# s^2C(s)-sy(0)-y'(0) + 6(sC(s)-y(0)) + 2C(s) = 2(sR(s)-y(0)) + R(s)
equacao_em_s  = Eq(((s**2)*C(s)-s*y0-dy_0)+12*(s*C(s)-y0)+32*C(s), 2/(s**3))

# Resolve a equação para G(s) = C(s) / R(s)
G_s = solve(equacao_em_s, C(s))

num, den = fraction(G_s[0])

ft1 = TransferFunction(num, den, s)
#PLOTA O GRÁFICO DE BODE
bode_plot(ft1, initial_exp=-1, final_exp=2)

